name: Workflow

on:
  workflow_dispatch: # manual trigger anytime
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  update-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: muhammadhammad2005
          THEME: transparent
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit Cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add profile-summary-card-output/transparent
          git commit -m "Auto-update transparent profile summary cards" || echo "No changes to commit"
          git push
